name: Daily Commit Workflow

on:
  schedule:
    - cron: "30 6 * * *"   # runs daily at 06:30 UTC
  workflow_dispatch:        # allow manual trigger

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 👇 include your email here exactly as required
      - name: Add timestamp file - 23f2000134@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > last-run.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add last-run.txt
          git commit -m "Automated daily update [skip ci]" || echo "No changes to commit"
          git push

